## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
array=np.random.randint(0, 20, size=15)
print(array)
array[(3<array) & (array<=8)] *= -1
print(array)

[19 13 16 14 18  4  3  7  5  0  6 12 16 10 10]
[19 13 16 14 18 -4  3 -7 -5  0 -6 12 16 10 10]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
array=np.random.randint(0, 20, size=15)
print(array)
print(np.where(array==array.max(),0,array))

[ 9 13 19 11  1 18 11  2 18  6  4 12 12  4  2]
[ 9 13  0 11  1 18 11  2 18  6  4 12 12  4  2]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
def func(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(func(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
array1 = np.random.randint(0,5,(8,3))
array2 = np.random.randint(0,5,(2,2))
array3 = (array1[..., np.newaxis, np.newaxis] == array2)

rows = (array3.sum(axis=(1,2,3)) >= array2.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
A = np.array([   [1,8,3],
                 [1,1,2],
                 [0,0,2],
                 [1,1,1],
                 [9,2,3],
                 [8,8,7],
                 [0,0,5],
                 [2,2,3],
                 [2,2,2],
                 [8,8,8],
                ])
B = np.logical_and.reduce(A[:,1:] == A[:,:-1], axis=1)
С = A[~B]
print(С)

[[1 8 3]
 [1 1 2]
 [0 0 2]
 [9 2 3]
 [8 8 7]
 [0 0 5]
 [2 2 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
A = np.array([   [1,8,3,3,4],
                 [1,8,9,9,4],
                 [1,8,3,3,4],
                 [1,3,4,7,0],
                 [1,1,1,1,1],
                 [1,1,1,1,1]])

print(np.unique(A, axis=0))

[[1 1 1 1 1]
 [1 3 4 7 0]
 [1 8 3 3 4]
 [1 8 9 9 4]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
array1=([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

def prod_func1(array1):
    n=len(array1) # количество строк
    m=len(array1[0]) # количество столбцов 
    p = 1;
    for i in range(n):
        for j in range(m):
            if (i == j):
                if array1[i][j]!=0:
                    p = p * array1[i][j];
    print(p)

prod_func1(array1)

#numpy

array2=np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

def prod_func2(array2):
    diag = np.diag(array2)
    print(diag[diag != 0].prod())

prod_func2(array2)



3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [20]:
x1=[1, 2, 2, 4]
y1=[4, 2, 1, 2]


def func1(x1,y1):
    if(len(x1) != len(y1)):
        return False
    x1.sort()
    y1.sort()
    for i in range(len(x1)):
        if(x1[i] != y1[i]):
            return False
    return True
    
print(func1(x1,y1))


#numpy

x2 = np.array([1, 2, 2, 4])
y2 = np.array([4, 2, 1, 2])

def func2(x2,y2):
    x_set,x_count=np.unique(x2,return_counts=True)
    y_set,y_count=np.unique(y2,return_counts=True)
    if(np.shape(x_set) != np.shape(y_set)):
        return False
    if(np.any(x_set != y_set) or np.any(x_count != y_count)):
        return False
    return True

print(func2(x2,y2))


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [21]:
x1=([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
def func1(x1):
    print(max(x1[i] for i in range(1, len(x1)) if not x1[i-1]))

func1(x1)    


#numpy
    
x2 = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 

def func2(x2):
    zero = x2==0
    print (x2[1:][zero[:-1]].max())

func2(x2)


5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
x1 =([2, 2, 2, 3, 3, 3, 5])

def func1(x1):
    list1=list()
    list2=list()
    keys=list()
    values=list()
    d={}
    counter=1
    for i in range(len(x1)):
        if x1[i] in list1:
            counter  =counter + 1
            d.update({x1[i]:counter}) 
        else:
            list1.append(x1[i])
            counter=1
            d={x1[i]:counter}
            list2.append(d)
    for i in list2:
        keys.append(list(i))
        values.append(list(i.values()))
    return sum(keys, []),sum(values, [])
    
print(func1(x1))


def run_length_encoding_non_vect(x1):
    val_list = [x[0]]
    num_list = list()
    counter = 1
    for i in range(1, len(x)):
        if(x[i - 1] == x[i]):
            counter = counter + 1
        else:
            val_list.append(x[i])
            num_list.append(counter)
    num_list.append(counter)
    return (val_list, num_list)



#numpy

x2 = np.array([2, 2, 2, 3, 3, 3, 5])
def func2(x2):
    x_set,x_count=np.unique(x2,return_counts=True)
    return (np.array(x_set),np.array(x_count))

print(func2(x2))


def run_length_encoding_vect(x2):
    y = np.hstack((np.ones(1), x[:- 1]))
    first_positions = x != y
    first_positions[0] = True
    indexes_1 = np.arange(np.size(x))[first_positions]
    indexes_2 = np.hstack((indexes_1[1:], np.array([np.size(x)])))

    return x[first_positions], indexes_2 - indexes_1




([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1], dtype=int64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [18]:
import math

X1=([[9, 5, 1],[6, 5, 0],[2, 1, 7],[3, 9, 9],[9, 0, 0]])
Y1=([[1, 7, 1],[0, 0, 2],[5, 8, 2],[9, 3 ,4]])

def func1(X1,Y1):
    result=list()
    for i in range(len(X1)):
        list1=list()
        for j in range(len(Y1)):
            dist = 0
            for k in range(len(X1[0])):
                dist += (X1[i][k] - Y1[j][k]) ** 2
            list1.append(math.sqrt(dist))
        result.append(list1)
    return result

print(func1(X1,Y1))


#numpy


X2=np.array([[9, 5, 1],[6, 5, 0],[2, 1, 7],[3, 9, 9],[9, 0, 0]])

Y2=np.array([[1, 7, 1],[0, 0, 2],[5, 8, 2],[9, 3 ,4]])


def func2(X2,Y2):
    return np.sqrt(np.sum((X2[:, np.newaxis] - Y2) ** 2, axis=-1))

func2(X2,Y2)

[[8.246211251235321, 10.344080432788601, 5.0990195135927845, 3.605551275463989], [5.477225575051661, 8.06225774829855, 3.7416573867739413, 5.385164807134504], [8.54400374531753, 5.477225575051661, 9.1104335791443, 7.874007874011811], [8.48528137423857, 11.789826122551595, 7.3484692283495345, 9.848857801796104], [10.677078252031311, 9.219544457292887, 9.16515138991168, 5.0]]


array([[ 8.24621125, 10.34408043,  5.09901951,  3.60555128],
       [ 5.47722558,  8.06225775,  3.74165739,  5.38516481],
       [ 8.54400375,  5.47722558,  9.11043358,  7.87400787],
       [ 8.48528137, 11.78982612,  7.34846923,  9.8488578 ],
       [10.67707825,  9.21954446,  9.16515139,  5.        ]])

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [128]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [115]:
averege_calories=np.mean(calorie_stats)
print('mean=',averege_calories)
averege_calories-60

mean= 106.88311688311688


46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [120]:
calorie_stats_sorted=np.sort(calorie_stats) 
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [114]:
median_calories=np.median(calorie_stats)
print('mediana=',median_calories)

mediana= 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [124]:
print(np.percentile(calorie_stats,75))
print(np.percentile(calorie_stats,50))
print(np.percentile(calorie_stats,25))
print(np.percentile(calorie_stats,10))
print(np.percentile(calorie_stats,5))
nth_percentile=np.percentile(calorie_stats,4)
print('nth_percentile=',nth_percentile)


110.0
110.0
100.0
90.0
70.0
nth_percentile= 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [126]:
more_calories=np.mean(calorie_stats>60)
more_calories*100

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [110]:
calorie_std=np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [129]:
Выводы:
    
Медиана количества калорий составляет 110,а среднее значение равно 106,9,со стандартным отклонением 19,4.
По количеству калорий CrunchieMunchies находится в 4-м процентиле по отношению ко всем другим хлопьям для завтрака.
96% других злаков содержат больше калорий, чем CrunchieMunchies.
Из 77 сухих завтраков только три имеют меньше калорий, чем CrunchieMunchies.


SyntaxError: invalid syntax (1299159538.py, line 1)